anatomy-typesystem/pom.xml, anatomy-typesystem/src/main/assembly/doc.xml, anatomy-typesystem/src/main/resources/META-INF/org.apache.uima.fit/types.txt, anatomy-typesystem/src/main/resources/de/averbis/textanalysis/typesystems/health/AnatomyTypeSystem.xml, pom.xml
adding anatomy concept by introducing a new submodule
=> #4: adding anatomy concept

anatomy-typesystem/src/main/resources/de/averbis/textanalysis/typesystems/health/AnatomyTypeSystem.xml, simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
Introducing types for anatomy annotations.
=> added anatomy types.

clinical-section-typesystem/src/main/resources/de/averbis/textanalysis/typesystems/health/ClinicalSectionTypeSystem.xml, medication-typesystem/src/main/resources/de/averbis/textanalysis/typesystems/health/MedicationTypeSystem.xml
- Introduce InpatientMedicationSection type
- Add "INACTIVE" to the available values of MedicationStatus
=> Medication extension

.github/workflows/build-pr.yml, .github/workflows/build-snapshot.yml, .travis.yml, pom.xml
- Remove Travis config
- Add GitHub action build configs
- Update distribution management in POM
=> #31 - Switch to GitHub actions

simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
=> #33 - Extend Medication with features 'dosage' and 'atcCodes'

components-health-typesystem/pom.xml, components-health-typesystem/src/main/java/de/averbis/textanalysis/types/health/HealthTypeSystemDescriptionProvider.java, components-health-typesystem/src/main/resources/META-INF/services/org.apache.uima.spi.JCasClassProvider, components-health-typesystem/src/main/resources/META-INF/services/org.apache.uima.spi.TypeSystemDescriptionProvider, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/EHRInformationTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/InternalTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/LaboratoryValueTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/MedicalNegationTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/MedicationTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/ObservationTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/PHITypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/PathologyTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/PatientInformationTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/ProcedureTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/TNMTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/TherapyTypeSystem.xml, components-health-typesystem/src/test/java/de/averbis/textanalysis/typesystems/health/ResolveTypeSystemTest.java, patient-information-typesystem/src/test/java/de/averbis/textanalysis/typesystems/health/ResolveTypeSystemTest.java
- Update the imports in the type system files to import the now main TS files instead of their proxies
- Added SPI types and JCas classes to components-health-typesystem
=> Issue #40: Resolve split packages

.github/workflows/build-pr.yml, .github/workflows/build-snapshot.yml, pom.xml
- uimaj 3.4.0 -> 3.4.1
- ruta 3.3.0-SNAPSHOT -> 3.3.0
- update github actions
=> Issue #44: Update dependencies

simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
extend PathologyDocumentation with new feature psaValue
=> extend PathologyDocumentation with new feature psaValue

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/OncologyTypeSystem.xml, simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
- add new features and adjust external typesystem
=> Issue 64: Extend GleasonScore and PathologyScores with new features

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/PathologyTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/TNMTypeSystem.xml, simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
=> Issue #70: New features to represent TNM prefixes and symbols

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/ObservationTypeSystem.xml, simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
=> Issue #74: Extend BloodPressure type with new features

clinical-section-typesystem/src/test/java/de/averbis/textanalysis/typesystems/health/ResolveTypeSystemTest.java, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/ClinicalSectionTypeSystem.xml, internal-typesystem/src/test/java/de/averbis/textanalysis/typesystems/health/ResolveTypeSystemTest.java
- extend typesystem
- adjust tests
=> Issue #72: extend clinical section typesystem with new types

simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
=> Issue #76: Rename BloodPressure features

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/ClinicalSectionTypeSystem.xml, simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
- add "confidence" to external ClinicalSection
- add "endIndicator" to ClinicalSectionCandidate
=> Issue #80: add confidence to clinical section

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/PatientInformationTypeSystem.xml, simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml
* Extending the PatientInformation with feature hospitalisation
* Extending Hospitalisation with feature focal
* ...
=> 84 add feature hospitalisations to internal and external patientinformation

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/OncologyTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/PathologyTypeSystem.xml, internal-typesystem/src/test/java/de/averbis/textanalysis/typesystems/health/ResolveTypeSystemTest.java, oncology-typesystem/src/test/java/de/averbis/textanalysis/typesystems/health/ResolveTypeSystemTest.java, pathology-typesystem/src/test/java/de/averbis/textanalysis/typesystems/health/ResolveTypeSystemTest.java
* added new type
* moved some types
* ...
=> Oncological information on document level

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/OncologyTypeSystem.xml
=> Issue #83: Oncological information on document level

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/ObservationTypeSystem.xml
=> 91 Introduce new feature "status" for AbstractObservations

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/LaboratoryValueTypeSystem.xml
- Add "category" to LaboratoryConcept
* ...
* ...
=> Issue #97: Add feature category to LaboratoryConcept

components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/PHITypeSystem.xml
- added types
- improved descriptions
* ...
* ...
=> Issue #104: Extend PHI Typesystem

components-health-typesystem/src/main/java/de/averbis/textanalysis/types/health/HealthTypeSystemDescriptionProvider.java, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/BiomarkerTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/InternalTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/ObservationTypeSystem.xml, components-health-typesystem/src/main/resources/de/averbis/textanalysis/types/health/PathologyTypeSystem.xml, health-typesystems-parent/pom.xml, simplified-health-typesystem/src/main/resources/de/averbis/types/health/SimplifiedHealthTypeSystem.xml, simplified-health-typesystem/src/test/java/de/averbis/textanalysis/typesystems/health/ResolveTypeSystemTest.java
* add feature "additionals" to external PathoDocumentation
* add type PathologyAdditionalEntry
* deprecate external "scores"
* replace internal patho thickness with tumorThickness
=> Issue #103: adapt types for biomarkers

health-typesystems-parent/pom.xml, pom.xml
* assertj 3.26.3 -> 3.27.4
* slf4j 2.0.16 -> 2.0.17
* parent-pom-typesystems 4.2.1 -> 4.3.0
* developer id "averbis" added.
* junit 5.11.3 -> 5.11.4
* Added junit-platform at 1.11.4
* No specific test procedure
=> Issue #118: Update dependencies
